title: GeoOS
subtitle: "Rust Programming Language Tutorials"
description: "Rust Programming Language Tutorials"
author: spatial-go
language: en
timezone: UTC

url: https://learning-rust.github.io
root: /

theme: navy

deploy:
  type: git
  repo: git@github.com:learning-rust/learning-rust.github.io.git

highlight:
  enable: false

hljs:
  enable: true

google_analytics: UA-111784617-1
algolia:
  en:
    api_key: 219b278e94416804a2d4bb47b3bf3d0b
    index_name: learning_rust
github: spatial-go/geoos
